### ISSUE TITLE
Plugin requires Maven 3.5.1 and breaks deploy/install plugin

### ISSUE THREAD

**Issue by jakub-bochenski** [HubSpot/dependency-management-maven-plugin#13]
Please check https://github.com/jeremylong/DependencyCheck/issues/1054 it seems it's the same problem.

Running with maven 3.5 fixes the issue.

It's rather ironic that a static check plugin would blow up the build because it declares invalid requirements (not to mention it's rather hard to find the root cause)

Stack trace: https://gist.github.com/jakub-bochenski/08b7e9dce1823ef55c2335eb7e79fb14

**Comment by jhaber** [comment]
Interesting. I'm having trouble reproducing the build failures with Maven 3.3.9. Do you have an example project and build command that fails? I can try downgrading some of the Maven-related deps (or maybe putting them at scope provided?), but I'd like to have an example to test my changes on before cutting a new release.

Also, I'm not sure if we can downgrade the maven-plugin-plugin below 3.5 due to [this](https://github.com/google/guava/issues/3006) issue with Guava we ran into, but I don't think that should leak out.

**Comment by jhaber** [comment]
Nevermind, I was able to get it to fail on https://github.com/hubspot/dropwizard-guicier by running `/usr/local/Cellar/maven@3.3/3.3.9/bin/mvn com.hubspot.maven.plugins:dependency-management-maven-plugin:0.10:analyze install`

**Comment by jakub-bochenski** [comment]
OK then. I have this failing in a fairly small project so I can send you a minimal if you need it.

**Comment by jhaber** [comment]
I released version 0.11 of the plugin which should show up in Maven central soon. Can you try it out and let me know if it fixes things for you?

**Comment by jakub-bochenski** [comment]
I got tired of waiting and built 0.11 locally.
It seems to work now with Maven 3.3.9

**Comment by jhaber** [comment]
Thanks for confirming it's fixed and for taking the time to track down the issue. Sorry for all the hassle

**Comment by jakub-bochenski** [comment]
uw, thanks for the fast fix
